# Generated by Django 5.2.4 on 2025-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="statut",
            field=models.CharField(default="En attente", max_length=20),
        ),
    ]
